version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '127.0.0.1:33060:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '0.0.0.0:8080:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/assets:/home/assets/
    networks:
      - app-network